apiVersion: apps/v1
kind: Deployment
metadata:
  name: signalr-2-app
spec:
  selector:
    matchLabels:
      app: signalr-2-app
  replicas: 1
  template:
    metadata:
      labels:
        app: signalr-2-app
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "signalr-2"
        dapr.io/app-port: "80"
        dapr.io/app-ssl: "true"
        dapr.io/config: "tracing"
        dapr.io/enable-metrics: "true"
        dapr.io/metrics-port: "9090" 
    spec:      
      containers:
      - name: signalr-2
        image: harbor-repo.vmware.com/jedi/signalr:v1003
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"  
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"        
        - name: ASPNETCORE_URLS
          value: "http://+:80"
        - name: SEQ_ENDPOINT
          value: http://seq-service        
---
apiVersion: v1
kind: Service
metadata:
  name: signalr-2-service
spec:
  selector:
    app: signalr-2-app  
  ports:
    - protocol: TCP 
      port: 80
      targetPort: 80
